### PR TITLE
Make types specific

### PR DESCRIPTION
**Pull request by oxinabox**
This removed the abstract types from the struct.

### CODE REVIEW

**Comment by oxinabox** [comment]
@ahwillia  prod

**Comment by ahwillia** [comment]
Is this performance related?

**Comment by oxinabox** [comment]
> Is this performance related?

Yes.

This change avoids abstract types in containers.
As per the performance guide-lines

**Comment by mkborregaard** [comment]
why not merge this?

**Comment by ahwillia** [comment]
Apologies I thought that I had merged it.

**Pull request merged**
